{"name": "Проверка изменения данных пользователя без авторизацией", "status": "passed", "description": "Для неавторизованного пользователя система вернёт ошибку", "steps": [{"name": "Получение ответа при попытке обновиления данных неавторизованного пользователя ", "status": "passed", "parameters": [{"name": "new_payload", "value": "{'email': 'newmanalexa@gmail.com', 'password': 'Pa)13MYk', 'name': 'newmanalexa'}"}], "start": 1732111313174, "stop": 1732111313565}], "start": 1732111313151, "stop": 1732111313566, "uuid": "858457dd-ceb9-4ee6-b596-f91efe5cd655", "historyId": "ba72d6f23cfabf5ee2557b9a2e4f2790", "testCaseId": "ba72d6f23cfabf5ee2557b9a2e4f2790", "fullName": "tests.test_update_data_user.TestUpdateDataUser#test_update_data_user_unauth_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_update_data_user"}, {"name": "subSuite", "value": "TestUpdateDataUser"}, {"name": "host", "value": "ivan-STC"}, {"name": "thread", "value": "1294727-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_update_data_user"}]}